#!/bin/sh

subl -b --project /home/aghiles/Aghiles/Administration/2-Job_Search/Search_network/aghiles/aghiles.sublime-project /home/aghiles/Aghiles/Administration/2-Job_Search/Search_network/aghiles/aghiles.tex
