#! /bin/sh
mypath=`realpath $0`
directory=`dirname $mypath`
filename=`basename $0`
echo $filename
filename=cv-fr

gedit ~/Aghiles/Administration/2-Job_Search/Search_computer/cv/$filename/$filename.tex
