#!/bin/sh

subl -b --project /home/aghiles/Aghiles/Administration/2-Job_Search/Search_network/aghiles/cl.sublime-project /home/aghiles/Aghiles/Administration/2-Job_Search/Search_network/aghiles/cl/cl.tex
