#! /usr/bin/env python
# [Gedit Tool]
# Name=JSONFormater
# Input=document
# Save-files=nothing
# Applicability=all
# Shortcut=<Primary><Alt>u
# Output=replace-document

 
import json
import sys
 
j = json.load(sys.stdin)
print json.dumps(j, sort_keys=True, indent=2)
