#!/bin/bash

directory="/home/aghiles/Aghiles/Tool/config/Calendar"
cd $directory

wget https://www.officeholidays.com/ics/ics_country_code.php?iso=FR -O $directory/fr.ics
wget https://www.officeholidays.com/ics/ics_country_code.php?iso=DZ -O $directory/dz.ics
curl "https://planning-paris.inseecu.net/Telechargements/ical/Edt_DJOUDI.ics?version=2018.0.3.1&idICal=C2301E3548B77560046787A7FD7E3B80&param=643d5b312e2e36325d2666683d3126663d31" -o $directory/Teaching.ics

sed -r -i -z "s/\nDTSTART([^\n]*\n)(.[^U])/\nDTSTART\1DUE\1\2/g" *.ics
sed -r -i -z "s/(\n[^D][^\n]*\n)DUE([^\n]*)/\1DTSTART\2\nDUE\2/g" *.ics
sed -r -i -z "s/\n(DTSTART[^:]*:........)([^T])/\n\1T080000\2/g" *.ics
sed -r -i -z "s/DTSTART([^\n]*)\nDUE([^\n]*)/DTSTART\1\nDUE\1/g" *.ics
sed -r -i -z "s/VTODO/VEVENT/g" *.ics

gnome-calendar


#sed -r -i -z "s/DTSTART([^\n]*)/$(date +"%Y%m%d" -d "+1 days")/g" Test.ics

#sed -r -i -z "s/\nDTSTART([^\n]*\n)(.[^U])/\nDTSTART\1DUE\1\2/g" $directory/*.ics
#sed -r -i -z "s/(\n[^D][^\n]*\n)DUE([^\n]*)/\1DTSTART\2\nDUE\2/g" $directory*.ics
#sed -r -i -z "s/DTSTART([^\n]*)\nDUE([^\n]*)/DTSTART\1\nDUE\1/g" $directory/*.ics
#sed -r -i -z "s/VTODO/VEVENT/g" *.ics

#sed -r -i "s/DTSTART;VALUE=DATE:[0-9]+\n[^D][^U][^E]/DTSTART;VALUE=DATE:\1\nDUE;VALUE=DATE:\1/g" *.ics
#sed -r -i "s/[^D][^S][^T].*DUE;VALUE=DATE:(.*)/DTSTART;VALUE=DATE:\1\nDUE;VALUE=DATE:\1/g" *.ics


