#!/bin/bash

mypath=`realpath $0`
directory=`dirname $mypath`
filename=`basename $directory`
cd $directory

git config --global user.email "papierpourgithub@gmail.com"
git remote add $filename https://github.com/BRICOMATA8/$filename.git

git add -v .
git commit -m "commit"
git pull -f $filename master
#firefox https://github.com/BRICOMATA8/$filename.git

cp -r -v \
	config/.Renviron \
	config/.zotero \
	config/.hidden \
	~/
cp -r -v config/gedit-config/gedit ~/.config/
cp -r -v config/gedit-local-share/gedit ~/.local/share/
cp -r -v config/extensions ~/.mozilla/firefox/*.default/
#cp -r -v config/"Local Storage" ~/.config/Mailspring/
