#!/bin/bash

mypath=`realpath $0`
directory=`dirname $mypath`
filename=`basename $directory`
cd $directory

#git config --global user.email "papierpourgithub@gmail.com"
#git remote add $filename https://BRICOMATA8@github.com/BRICOMATA8/$filename.git

git add -v .
git commit -m "commit"
git pull -f $filename master
#firefox https://github.com/BRICOMATA8/$filename.git

#mv -f /home/aghiles/.zotero /home/aghiles/.zotero2
#mv -f /home/aghiles/.config/gedit /home/aghiles/.config/gedit2
#mv -f /home/aghiles/.local/share/gedit /home/aghiles/.local/share/gedit2
#mv -f /home/aghiles/.mozilla/firefox/*.default/extensions /home/aghiles/.mozilla/firefox/extensions2 

ln -sf $directory/config/.hidden /home/aghiles/.hidden
ln -sf $directory/config/.bashrc /home/aghiles/.bashrc
ln -sf $directory/config/.bash_history /home/aghiles/.bash_history
ln -sf $directory/config/.Renviron /home/aghiles/.Renviron
ln -sf $directory/config/.zotero /home/aghiles/.zotero
ln -sf $directory/config/gedit-config /home/aghiles/.config/gedit
ln -sf $directory/config/gedit-local-share /home/aghiles/.local/share/gedit
ln -sf $directory/config/extensions /home/aghiles/.mozilla/firefox/*.default/extensions


