#!/bin/bash

mypath=`realpath $0`
directory=`dirname $mypath`
filename=`basename $directory`
cd $directory

#git config --global user.email "papierpourgithub@gmail.com"
#git remote add $filename https://BRICOMATA8@github.com/BRICOMATA8/$filename.git

git add -v .
git commit -m "commit"
git pull -f $filename master
#firefox https://github.com/BRICOMATA8/$filename.git


#ln -sf /home/aghiles/Aghiles/Tool/config/.hidden /home/aghiles/.hidden
#ln -sf /home/aghiles/Aghiles/Tool/config/.bashrc /home/aghiles/.bashrc
#ln -sf /home/aghiles/Aghiles/Tool/config/.bash_history /home/aghiles/.bash_history
#ln -sf /home/aghiles/Aghiles/Tool/config/.Renviron /home/aghiles/.Renviron
#ln -sf /home/aghiles/Aghiles/Tool/config/preferences.txt /home/aghiles/.arduino/preferences.txt
#ln -sf /home/aghiles/Aghiles/Tool/config/gvfs-metadata ~/.local/share/

#rm -rf /home/aghiles/.zotero
#ln -sf /home/aghiles/Aghiles/Tool/config/.zotero /home/aghiles/.zotero

#rm -rf /home/aghiles/.config/gedit
#rm -rf /home/aghiles/.local/share/gedit
#ln -sf /home/aghiles/Aghiles/Tool/config/gedit-config /home/aghiles/.config/gedit
#ln -sf /home/aghiles/Aghiles/Tool/config/gedit-local-share /home/aghiles/.local/share/gedit

#rm -rf '/home/aghiles/.config/Mailspring/Local Storage'
#ln -sf /home/aghiles/Aghiles/Tool/config/dregetece/* /home/aghiles/.config/Mailspring/

#rm -rf ~/.local/share/nautilus/scripts
#ln -sf /home/aghiles/Aghiles/Tool/config/scripts ~/.local/share/nautilus/

#ln -sf /home/aghiles/Aghiles/Tool/config/tsrdeple /home/aghiles/.config/chromium

ln -sf /home/aghiles/Aghiles/Tool/config/subrid /home/aghiles/.config/sublime-text-3


#rm -rf /home/aghiles/.mozilla/firefox/*.default/extensions
#ln -sf /home/aghiles/Aghiles/Tool/config/extensions /home/aghiles/.mozilla/firefox/*.default/

