#!/bin/sh

sudo apt install git


cd /home/aghiles/Aghiles/Tool/bin
# Contiki
git clone https://github.com/contiki-os/contiki.git
cd contiki && git submodule update --init --recursive
cd tools/cooja && git submodule update --init


cd /home/aghiles/Aghiles

# Program
git clone git://github.com/BRICOMATA8/Program

# Redaction
git clone git://github.com/BRICOMATA8/Redaction

for d in `seq 0 5`; do 
chmod u+x /home/aghiles/Aghiles/Redaction/$d/paper/compile;
chmod u+x /home/aghiles/Aghiles/Redaction/$d/slide/compile;
done
chmod u+x /home/aghiles/Aghiles/Redaction/cv/*/compile

# Formation
git clone git://github.com/BRICOMATA9/Formation

# Teaching
git clone git://github.com/BRICOMATA9/Teaching



