#!/bin/bash

IFS='
'
for arg in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do
	gvfs-set-attribute -t string $arg 'metadata::custom-icon' 'file:///home/aghiles/Aghiles/Tool/config/green.svg'
	touch "$arg"
done


#/home/aghiles/.local/share/folder-color/icons/
