#!/bin/bash

IFS='
'
for arg in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do
	gvfs-set-attribute -t string $arg 'metadata::custom-icon' 'file:///home/aghiles/Aghiles/Tool/config/icon.svg'
	touch "$arg"
done

