#! /bin/sh
mypath=`realpath $0`
directory=`dirname $mypath`
folder=`basename $directory`
filename=`basename $0`
filename=0
folder=paper

ty="_$folder.sublime-project"
subl -b --project /home/aghiles/Aghiles/Redaction/$filename/$filename$ty /home/aghiles/Aghiles/Redaction/$filename/$folder/$folder.tex

