#!/bin/sh

#gedit These/Program/C/Contiki/home/sdn-wise-contiki/sdn-wise/node-conf.c &
#gnome-terminal --working-directory=These/Program/C/Contiki -e "sh contiki"

nautilus /home/aghiles/Aghiles/Teaching
