#!/bin/bash
# [Gedit Tool]
# Save-files=document
# Languages=
# Name=compile
# Shortcut=<Alt>x
# Input=document
# Output=output-panel
# Applicability=all


cd $GEDIT_CURRENT_DOCUMENT_DIR
./compile $GEDIT_CURRENT_DOCUMENT_PATH
cd ..
./compile $GEDIT_CURRENT_DOCUMENT_PATH
cd ..
./compile $GEDIT_CURRENT_DOCUMENT_PATH
