#!/bin/bash
# [Gedit Tool]
# Output=output-panel
# Applicability=all
# Shortcut=<Alt>w
# Save-files=document
# Input=document
# Name=tikz


echo $GEDIT_CURRENT_DOCUMENT_NAME
cd $GEDIT_CURRENT_DOCUMENT_DIR
./compile $GEDIT_CURRENT_DOCUMENT_NAME
cd ..
./compile $GEDIT_CURRENT_DOCUMENT_NAME
cd ..
./compile $GEDIT_CURRENT_DOCUMENT_NAME
