#!/bin/bash

ln -sf /home/aghiles/Aghiles/Tool/config/.hidden /home/aghiles/.hidden

ln -sf /home/aghiles/Aghiles/Tool/config/.bashrc /home/aghiles/.bashrc

ln -sf /home/aghiles/Aghiles/Tool/config/.bash_history /home/aghiles/.bash_history

ln -sf /home/aghiles/Aghiles/Tool/config/.Renviron /home/aghiles/.Renviron

ln -sf /home/aghiles/Aghiles/Tool/config/common /home/aghiles/snap/mailspring/

rm -rf ~/.local/share/nautilus/scripts
ln -sf /home/aghiles/Aghiles/Tool/config/scripts ~/.local/share/nautilus/
chmod -R u+x ~/.local/share/nautilus/scripts

rm -rf /home/aghiles/zotero
ln -sf /home/aghiles/Aghiles/Tool/config/zotero /home/aghiles/.zotero

ln -s /home/aghiles/Aghiles/Tool/config/mozilla /home/aghiles/.mozilla

ln -s /home/aghiles/Aghiles/Tool/config/zotero /home/aghiles/.zotero

ln -s /home/aghiles/Aghiles/Tool/config/sublim /home/aghiles/.config/sublime-text-3

ln -s /home/aghiles/Aghiles/Tool/config/gedit/config  /home/aghiles/.config/gedit
ln -s /home/aghiles/Aghiles/Tool/config/gedit/local-share /home/aghiles/.local/share/gedit 

ln -s /home/aghiles/Aghiles/Tool/config/arduino/arduino-cli.yaml /home/aghiles/.arduino15/arduino-cli.yaml
ln -s /home/aghiles/Aghiles/Tool/config/arduino/preferences.txt /home/aghiles/.arduino15/preferences.txt




