#! /bin/sh
mypath=`realpath $0`
directory=`dirname $mypath`
folder=`basename $directory`
filename=`basename $0`
filename=3
folder=slide

ty="_$folder.sublime-project"
subl -b --project Aghiles/Redaction/$filename/$filename$ty Aghiles/Redaction/$filename/$folder/$folder.tex

