#!/bin/sh
# [Gedit Tool]
# Name=bib
# Input=selection
# Output=insert
# Applicability=all
# Save-files=nothing
# Shortcut=<Primary><Shift>greater


sed -z -r '
	s/\t\\aghiles([^}]*)}/\t\tnotkeyword=\1},/g
	s/(.*)/\t\\printbibliography\[heading=subbibliography,\n\t\t\1\t\ttitle=Others\n\t\]/g'
