#! /bin/sh
mypath=`realpath $0`
directory=`dirname $mypath`
filename=`basename $0`
echo $filename
filename=lm-fr

gedit ~/Aghiles/Administration/Job_x_Search/Search_computer/cv/$filename/$filename.tex
