#!/bin/bash

#gtk-launch firefox ~/Aghiles/Firefox/Tool/english_Grammarly.desktop
#xdg-open ~/Aghiles/Firefox/Tool/text_editor.desktop

/home/aghiles/Aghiles/Tool/commands/trad/1
#xdg-open https://www.mytextarea.com/
