#!/bin/bash


export PATH=$PATH:/home/aghiles/Downloads/Matlab/bin:/usr/local/MATLAB/R2016b/bin

title1="Redaction"

titl1=/home/aghiles/Aghiles/Program/plot_m_lora

cmd="matlab"

gnome-terminal \
				--tab --title="$title1" --command="bash -c 'cd $titl1; $cmd; $SHELL'" 


#cd /home/aghiles/Aghiles/Program/gw/Lora
#/usr/local/MATLAB/R2016b/bin/matlab &

