// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.normandy.first_run", false);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1567626484);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1567661594);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1567673467);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1567626288);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1567670032);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1567661834);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1567661714);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1567626036);
user_pref("browser.laterrun.bookkeeping.sessionCount", 26);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 66);
user_pref("browser.newtabpage.activity-stream.impressionId", "{d172c0dd-2a3b-447e-8e0b-2294f81595f8}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1567634400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1567626076);
user_pref("browser.onboarding.notification.prompt-count", 5);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\",\"jid1-qofqdk4qzufgwq_jetpack\"],\"idsInUrlbar\":[\"pocket\",\"jid1-qofqdk4qzufgwq_jetpack\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1567672922278");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1567676522278");
user_pref("browser.search.countryCode", "FR");
user_pref("browser.search.region", "FR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190709221323");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1567674432");
user_pref("browser.slowStartup.averageTime", 743);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190709221323");
user_pref("browser.startup.homepage_override.mstone", "60.8.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"languagetool-webextension_languagetool_org-browser-action\",\"zotero_chnm_gmu_edu-browser-action\",\"bibitnow018_aqpl_mc2_chalmers_se-browser-action\",\"chrome-gnome-shell_gnome_org-browser-action\",\"button_scholar_google_com-browser-action\",\"jid1-qofqdk4qzufgwq_jetpack-browser-action\",\"_be4c6348-e64f-4ff9-9e48-47468de8aa64_-browser-action\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\",\"languagetool-webextension_languagetool_org-browser-action\",\"zotero_chnm_gmu_edu-browser-action\",\"bibitnow018_aqpl_mc2_chalmers_se-browser-action\",\"chrome-gnome-shell_gnome_org-browser-action\",\"button_scholar_google_com-browser-action\",\"jid1-qofqdk4qzufgwq_jetpack-browser-action\",\"_be4c6348-e64f-4ff9-9e48-47468de8aa64_-browser-action\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1567626040019");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "60.8.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.lastModified", "Wed, 28 Aug 2019 19:55:12 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1567626485);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190709221323");
user_pref("extensions.lastAppVersion", "60.8.0");
user_pref("extensions.lastPlatformVersion", "60.8.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", false);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"760cd8bb-a341-4461-b2da-6bb651c89878\",\"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\":\"42411638-4f0f-41f4-98b6-3b28740e579f\",\"jid1-QoFqdK4qzUfGWQ@jetpack\":\"48d02e77-0929-446e-ab05-3746ec3e55c3\",\"{b9acf540-acba-11e1-8ccb-001fd0e08bd4}\":\"3ec22540-823f-4123-b6aa-0887e21bb6d7\",\"gitzip-firefox-addons@gitzip.org\":\"1dbfe40e-ffee-4215-842e-eb661cc76102\",\"button@scholar.google.com\":\"9e6667ff-9959-43b7-926f-faaee2426370\",\"bibitnow018@aqpl.mc2.chalmers.se\":\"3c88f7ce-09d6-4c2a-8ee3-190d6ac17047\",\"@mendeleyimporter\":\"6669cb96-7a81-4594-b04d-3ffcd57b2976\",\"translator@zoli.bod\":\"e9795cc4-492d-457e-8d31-af8810311d71\",\"zotero@chnm.gmu.edu\":\"028c8942-3337-4357-88c1-0e5a34e6bb67\",\"hotspot-shield@anchorfree.com\":\"8a611239-fbd3-4692-a798-3ec080587ef0\",\"{03e07985-30b0-4ae0-8b3e-0c7519b9bdf6}\":\"d3d96361-e4e7-45c8-acb8-86a194f63efc\",\"chrome-gnome-shell@gnome.org\":\"33717198-a6b0-4de8-9efa-687c84ad45cb\",\"languagetool-webextension@languagetool.org\":\"fe0fa5f7-eda4-4a97-a757-576467b59ccb\",\"{be4c6348-e64f-4ff9-9e48-47468de8aa64}\":\"41094440-afea-4685-9465-0da5976ff82b\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1567626487);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190709221323");
user_pref("media.gmp-manager.lastCheck", 1567670081);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("security.sandbox.content.tempDirSuffix", "d723fcdd-8702-4ded-af14-c7ba75c45377");
user_pref("services.blocklist.addons.checked", 1567661561);
user_pref("services.blocklist.clock_skew_seconds", 33);
user_pref("services.blocklist.gfx.checked", 1567661561);
user_pref("services.blocklist.last_etag", "\"1567621920756\"");
user_pref("services.blocklist.last_update_seconds", 1567661561);
user_pref("services.blocklist.onecrl.checked", 1567661561);
user_pref("services.blocklist.pinning.checked", 1567661561);
user_pref("services.blocklist.plugins.checked", 1567661561);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1567674430);
user_pref("toolkit.telemetry.cachedClientID", "149e0dd8-d8f6-4a0f-9232-24f3c993433b");
user_pref("toolkit.telemetry.previousBuildID", "20190709221323");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
