#!/bin/sh

Aghiles/Latex/src/these/compile &
Aghiles/Latex/src/these_slide/compile &
Aghiles/Latex/src/paper0/compile &
Aghiles/Latex/src/paper0_slide/compile &
Aghiles/Latex/src/survey0/compile &
#sh Aghiles/Latex/src/survey0_slide/compile &

gedit --new-window Aghiles/Latex/src/these/these.tex &
gedit --new-window Aghiles/Latex/src/these_slide/these_slide.tex &
gedit --new-window Aghiles/Latex/src/paper0/paper0.tex &
gedit --new-window Aghiles/Latex/src/paper0_slide/paper0_slide.tex &
gedit --new-window Aghiles/Latex/src/survey0/survey0.tex &
#gedit --new-window Aghiles/Latex/src/survey0_slide/survey0_slide.tex &

Aghiles/Latex/bin/Zotero/zotero &
rstudio Aghiles/R/src/PI_enron/src/enron_mail.r &

#gnome-terminal --working-directory=Aghiles/Latex/res/storage &
#thunderbird &
#gnome-calendar &



