#!/bin/bash
mypath=`realpath .`
directory=`dirname "$mypath"`
filename=`basename "$mypath"`

#export TEXINPUTS=res/tikz:$TEXINPUTS
latexmk -f -cd -lualatex -output-directory=bin -shell-escape -jobname=$filename $filename.tex
evince bin/$filename.pdf

#rm .*
#rm src/.*
#rm src/*/.*
for f in *.tex ; do
echo "[LATEX]
master-filename = $filename.tex" > "`dirname "$f"`/.`basename "$f"`.ini" ; 
done
for f in src/*.tex ; do
echo "[LATEX]
master-filename = ../$filename.tex" > "`dirname "$f"`/.`basename "$f"`.ini" ; 
done
for f in src/*/*.tex ; do
echo "[LATEX]
master-filename = ../../$filename.tex" > "`dirname "$f"`/.`basename "$f"`.ini" ; 
done
